[package]
name = "core"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
sqlx = { version = "0.8.6", features = ["sqlite", "time", "runtime-tokio"] }
